# permissions for end users to view keplermachineconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keplermachineconfig-viewer-role
rules:
- apiGroups:
  - addons.operator.com
  resources:
  - keplermachineconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - addons.operator.com
  resources:
  - keplermachineconfigs/status
  verbs:
  - get
