# permissions for end users to view keplerintegrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keplerintegration-viewer-role
rules:
- apiGroups:
  - dependency.kepler.operator.com
  resources:
  - keplerintegrations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dependency.kepler.operator.com
  resources:
  - keplerintegrations/status
  verbs:
  - get
