# permissions for end users to edit keplerintegrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keplerintegration-editor-role
rules:
- apiGroups:
  - dependency.kepler.operator.com
  resources:
  - keplerintegrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dependency.kepler.operator.com
  resources:
  - keplerintegrations/status
  verbs:
  - get
