# permissions for end users to edit keplerdependencies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keplerdependencies-editor-role
rules:
- apiGroups:
  - system.operator.com
  resources:
  - keplerdependencies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - system.operator.com
  resources:
  - keplerdependencies/status
  verbs:
  - get
