# permissions for end users to view keplerdependencies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keplerdependencies-viewer-role
rules:
- apiGroups:
  - system.operator.com
  resources:
  - keplerdependencies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - system.operator.com
  resources:
  - keplerdependencies/status
  verbs:
  - get
