name: docs checker

on:
  pull_request:

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-go@main
        with:
          go-version-file: go.mod

      - name: make docs
        run: |
          make docs
          git diff --exit-code
