name: Integration test
on:
  pull_request:
    branches:
      - v1alpha1
env:
  KIND_VERSION: "0.15.0"
  GO111MODULE: "on"
  OPERATOR_IMAGE: "quay.io/sustainable_computing_io/kepler-operator"
  KUBECONFIG: /tmp/.kube/config
  KIND_WORKER_NODES: 2
  
jobs:
  e2e:
    name: e2e
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@main
        with:
          go-version-file: go.mod
          cache: true

      - name: Install all tools
        run: make tools
      - name: use kepler action for kind cluster build
        uses: sustainable-computing-io/kepler-action@v0.0.1
        with:
          cluster_provider: kind
          runningBranch: kind
      - name: Ensure cluster is able to run OLM bundles
        run: make cluster-prereqs

      - uses: ./.github/compute-version
        id: version

      - name: Run e2e tests
        run: |
          ./tests/run-e2e.sh --ci
        env:
          VERSION: ${{ steps.version.outputs.version }}

      - name: Capture cluster state
        if: always()
        shell: bash
        run: |
          # Capture apiserver state
          # TODO: enable this when we have oc installed as part of `make tools`
          # oc adm inspect node --dest-dir cluster-state || true
          # oc adm inspect -A statefulset --dest-dir cluster-state || true
          # oc adm inspect -A deployment --dest-dir cluster-state || true
          # oc adm inspect -A ns --dest-dir cluster-state || true
          cp -r tmp/e2e cluster-state/ || true

      - name: Archive production artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cluster-state
          path: cluster-state
